### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by adiusz** [molebox/gatsby-theme-overreacted-toggle#5]
Hello. 
I have a strange error while building site using this theme:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Unexpected character '�' (1:0)

File: node_modules/gatsby-theme-overreacted-toggle/assets/sun.png:1:0


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Unexpected character '�' (1:0)

File: node_modules/gatsby-theme-overreacted-toggle/assets/moon.png:1:0

failed Building development bundle - 6.493s
```

Any idea what is going on? I tried to swap icons with downloaded ones. Same effect.

**Comment by molebox** [comment]
Hey! Hmm not sure, i can take a look and get back to you. Give me a couple of days, got alot on at the moment :-)

**Comment by adiusz** [comment]
sure thing @molebox :) I'll be there

**Comment by molebox** [comment]
Looking into this now

**Comment by molebox** [comment]
Im not sure if the problem was because webpack couldn't locate the png files, so i moved them alongside the component. Works locally. Ive published a new version 1.0.3. Let me know if that fixes it for you. :-)

**Comment by adiusz** [comment]
it works like a charm, thanks 👍

**Comment by adiusz** [comment]
Just one more thing, the icons aren't exactly centered in Y axis. 

<img width="56" alt="Zrzut ekranu 2020-08-19 o 13 54 16" src="https://user-images.githubusercontent.com/20825919/90631712-7d2c2800-e223-11ea-8df4-701f00b2b585.png">

Little flexbox would be fine ;)

**Comment by molebox** [comment]
> Just one more thing, the icons aren't exactly centered in Y axis.
> 
> <img alt="Zrzut ekranu 2020-08-19 o 13 54 16" width="56" src="https://user-images.githubusercontent.com/20825919/90631712-7d2c2800-e223-11ea-8df4-701f00b2b585.png">
> 
> Little flexbox would be fine ;)

Great!

Hmm yeah, i must have missed that. Will correct it
